<a href="https://colab.research.google.com/github/rahuljha0810/myfirstpython/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

Arr= np.array([[4,5,6,3],[5,6,9,3]])
print(Arr)
print(Arr.sum(axis=1))

#we can add two array directly

print(Arr.T) #to transpose the array
for i in Arr.flat :
    print(i)
    
print(Arr)
print("Maximum at : ", Arr.argmax())



Arr1= np.ones((2,4))

#arr= np.identity(5,3)


Arr2= np.arange(14).reshape((2,7))

Arr2= Arr2.ravel()

Arr3= np.linspace(1,50, 5)



In [ ]:
# random number creation from numpy

A1=np.random.rand(2,3) # number between 0-1

#random.randint(low, high=None, size=None, dtype=int)
A2= np.random.randint(1,50, 5)
print(A2)
A3= np.random.random((5,5))

A=np.random.randint(5,100,(5,5))
print(A)
print(A[1:4, 1:4])

A=np.random.randn(5)
print(A)

A=np.full((3,4),45)
print(A)
a = np.eye(5)
print(a)

In [ ]:
# Get input from user in terms of expenses of last 5 months
# Calculate mean, max, min, max-min, max-mean, mean-min
# Generate a 2 dimentional array having information as follow
# info=[Em1, Em2, Em3,Em4,Em5
#      mean, max, min, max-min, max-mean, mean-min]


TmpEx=[]
for i in range(6):
  TmpEx.append(int(input("Enter Expense of Month "+str(i+1)+': ')))
print("the expenditure list is : ",TmpEx)

Inf=[np.mean(TmpEx),np.max(TmpEx),np.min(TmpEx),
     np.max(TmpEx)-np.min(TmpEx),np.max(TmpEx)-np.mean(TmpEx),
     np.mean(TmpEx)-np.min(TmpEx)]
print("the list of final : ",Inf)

MyArray=np.array([TmpEx,Inf])
print("final array : ", MyArray)

Enter Expense of Month 1: 42
Enter Expense of Month 2: 3
Enter Expense of Month 3: 65
Enter Expense of Month 4: 12
Enter Expense of Month 5: 45
Enter Expense of Month 6: 45
the expenditure list is :  [42, 3, 65, 12, 45, 45]
the list of final :  [35.333333333333336, 65, 3, 62, 29.666666666666664, 32.333333333333336]
final array :  [[42.          3.         65.         12.         45.         45.        ]
 [35.33333333 65.          3.         62.         29.66666667 32.33333333]]


In [ ]:
# print the expnses in diagonal form by using 
# slicing from above array info
# using diagonal array
# Hint:
# slice value of expense from info array
# and print using diagonal function of numpy

# syntax: A[rows,colmns]
print(np.diag(TmpEx))

[[42  0  0  0  0  0]
 [ 0  3  0  0  0  0]
 [ 0  0 65  0  0  0]
 [ 0  0  0 12  0  0]
 [ 0  0  0  0 45  0]
 [ 0  0  0  0  0 45]]


In [ ]:
A=np.random.randint(5,100,(5,5))
print(A)
print(A.max())
print(A.max(axis=1))
print(A.max(axis=0))

[[22 36 73 35 49]
 [95 62 73 39 26]
 [61 58 75 46 44]
 [28 51 92 39 29]
 [65 51 63 76 33]]
95
[73 95 75 92 76]
[95 62 92 76 49]


In [ ]:
print(A)
print(A.sum())
print(A.sum(axis=1))
print(A.sum(axis=0))

[[22 36 73 35 49]
 [95 62 73 39 26]
 [61 58 75 46 44]
 [28 51 92 39 29]
 [65 51 63 76 33]]
1321
[215 295 284 239 288]
[271 258 376 235 181]


In [ ]:
# Mathematical Operations in Array
A=np.random.randint(1,5,(2,2))
B=np.random.randint(1,5,(2,2))
print(A)
print(B)
#print(A+B)
#print(A-B)
#print(A*B)
print(A.dot(B))

In [ ]:
# Wap To generate 2 arrays of length 5x5
# The elements of first array must be float and in range of
# 5 to 50
# The second array have negative and positive elements
# As a output print the summation of both arrays
# print summation array in row wise sorted form

# Solution:
A1=np.random.randint(5,50,(5,5))*0.4
A2=np.random.randn(5,5)
print(A1)
print(A2)
A3=A1+A2
print(A3)
print(np.sort(A3,axis=1))
print(A3)

In [ ]:
A1=np.random.randint(1,5,(3,3))
A2=np.random.randint(1,5,(3,3))
print(A1)
print(A2)
# Joining
A3=np.array(list(A1)+list(A2))
print(A3)

In [ ]:
A=np.array([2,4,5,7,8,5])

A=np.delete(A,3)

A=np.append(A,45)

A=np.insert(A,2,45)

[2 4 5 8 5]


In [ ]:
# for joining Arrays
# stack
# vstack
# hstack
# dstack
# Search (search, sortsearch)
# Splitting (array_split)